In [ ]:
import pandas as pd
from actantial import OpenAIBackend, AnthropicBackend, HuggingFaceBackend
from actantial import run_extract, load_annotations, compare_annotations

In [3]:
df = pd.DataFrame({
    "id": [1, 2, 3],
    "text": ["Alice wants Bob", "Bob wants Alice", "Alice wants Bob, but Bob does not want Alice"],
})

## Annotations GPT

In [4]:
backend_gpt = OpenAIBackend("gpt-4o-mini")
backend_gpt.generate("What is the capital of France?")

'The capital of France is Paris.'

In [4]:
run_extract(
    data=df,
    backend=backend_gpt,
    output_dir="output",
    template="prompt_open",
)

Timestamp: 	20260608_160930
Log: 		output/logs/gpt-4o-mini_prompt_open_20260608_160930.log
Files: 		output/actantial_models/gpt-4o-mini/prompt_open/20260608_160930

100%|██████████| 3/3 [00:14<00:00,  4.87s/it]

## Annotations Claude

In [11]:
backend_claude = AnthropicBackend("claude-haiku-4-5")
backend_claude.list_templates()

['prompt_open']

In [13]:
run_extract(
    data=df,
    backend=backend_claude,
    output_dir="output",
    template="prompt_open",
)

Timestamp: 	20260608_161344
Log: 		output/logs/claude-haiku-4-5_prompt_open_20260608_161344.log
Files: 		output/actantial_models/claude-haiku-4-5/prompt_open/20260608_161344

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:09<00:00,  3.25s/it]

## Annotations Huggingface

In [14]:
backend_hf = HuggingFaceBackend(repository="google", model_name="gemma-3-1b-it")

Loading model google/gemma-3-1b-it...
Model loaded successfully

In [15]:
run_extract(
    data=df,
    backend=backend_hf,
    output_dir="output",
    template="prompt_open",
)

Timestamp: 	20260608_161408
Log: 		output/logs/gemma-3-1b-it_prompt_open_20260608_161408.log
Files: 		output/actantial_models/gemma-3-1b-it/prompt_open/20260608_161408

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:15<00:00,  5.21s/it]

## Load Annotations

In [16]:
annot_gpt = load_annotations(df, "output/actantial_models/gpt-4o-mini/prompt_open/20260608_160930")
annot_claude = load_annotations(df, "output/actantial_models/claude-haiku-4-5/prompt_open/20260608_161344")
annot_hf = load_annotations(df, "output/actantial_models/gemma-3-1b-it/prompt_open/20260608_161408")

annot_gpt.head(1)

,id,text,file_name,Subject,Object,Sender,Receiver,Helper,Opponent
0,1,Alice wants Bob,output/actantial_models/gpt-4o-mini/prompt_ope...,alice,bob,alice,bob,None,None

## Compare annotations

In [18]:
compare_annotations(
    dfs=[annot_gpt, annot_claude, annot_hf],
    metric="f1_micro"
)

          coder_0_coder_1  coder_0_coder_2  coder_1_coder_2  avg     N
Subject               1.0              1.0              1.0  1.0     9
Object                1.0              1.0              1.0  1.0     9
Sender                NaN              1.0              NaN  1.0     3
Receiver              NaN              1.0              NaN  1.0     3
Helper                NaN              NaN              NaN  NaN     0
Opponent              1.0              NaN              NaN  1.0     1
avg                   1.0              1.0              1.0  1.0  <NA>

## Create own templates

In [23]:
!actantial-init-templates "./test/"

Templates copied to 'test/templates'. Pass '--templates_dir test/templates' to use templates from this directory.

In [7]:
run_extract(
    data=df,
    backend=backend_gpt,
    output_dir="output",
    templates_dir="./test/templates", # new template directory, this is where you can add your own templates!
    template="prompt_open",
)

Timestamp: 	20260608_162647
Log: 		output/logs/gpt-4o-mini_prompt_open_20260608_162647.log
Files: 		output/actantial_models/gpt-4o-mini/prompt_open/20260608_162647

100%|██████████| 3/3 [00:06<00:00,  2.33s/it]

<i><b><center>Fin</center></b></i>